### ISSUE TITLE
integration error after opencti upgrade version to 5.12.27

### ISSUE THREAD

**Issue by mjounes2** [misje/wazuh-opencti#15]
![image](https://github.com/misje/wazuh-opencti/assets/113125062/91e56376-76a0-4ddf-b30c-5baa4dcfb10b)
![image](https://github.com/misje/wazuh-opencti/assets/113125062/d2653598-eca3-4463-9796-b22bd5d952a8)

**Comment by misje** [comment]
What version of OpenCTI are you upgrading from? What version of this integration are you running? What does your source event look like?

**Comment by mjounes2** [comment]
I upgraded to the latest version 5.12.27, and I got this error in the above image. right now I downgraded it to version 5.12.17 and it is working fine without issues. as you see in the screen shoot 
![image](https://github.com/misje/wazuh-opencti/assets/113125062/2c42e317-073a-4b48-8256-f17acb2829de)

![image](https://github.com/misje/wazuh-opencti/assets/113125062/6e795c85-7d59-43e8-b035-ba84c70e3128)

**Comment by misje** [comment]
OK, I've confirmed this. The graphql API has changed, seemingly without notice, because I haven't been able to find anything in changelogs. [This commit](https://github.com/OpenCTI-Platform/client-python/commit/16c8fe1429fe7b5baeb586146aabb774368bb174) is the closest thing I can find as a migration guide. I'll leave a fix in a merge request soon.
