### ISSUE TITLE
New Filters OpenCTI

### ISSUE THREAD

**Issue by Myskiv-Ivan** [misje/wazuh-opencti#9]
The configuration algorithm for the client API has been changed
https://github.com/OpenCTI-Platform/client-python/commit/c99eea915c93d005bd963d3533903d7574ce0f8a#diff-2b4f37ba44d71fbbc094b19c4d4a62a44ac18eba483de4c0a53344bbf94f2171

**Comment by AmmisettyBhuvanesh** [comment]
the graphql schema changed...so old code is not working

**Comment by misje** [comment]
I upgraded OpenCTI myself today and experienced this. Here is a [migration guide](https://docs.opencti.io/latest/reference/filters-migration/). I'll have a look.

**Comment by misje** [comment]
For some reason I never got a notification about this issue, otherwise I would have looked into it earlier. Would anyone please help testing the [changes I just pushed](https://github.com/misje/wazuh-opencti/blob/bug-9/use-new-filter-api/custom-opencti.py)? I haven't seen any errors on any real-world data yet, but it would be very helpful to get more eyes on the results before I merge.

**Comment by Myskiv-Ivan** [comment]
> For some reason I never got a notification about this issue, otherwise I would have looked into it earlier. Would anyone please help testing the [changes I just pushed](https://github.com/misje/wazuh-opencti/blob/bug-9/use-new-filter-api/custom-opencti.py)? I haven't seen any errors on any real-world data yet, but it would be very helpful to get more eyes on the results before I merge.


Hi
I took the modified script config and the filter for "GraphQL" works with the new filters
So far there have been no problems
I'm trying to finalize the script for FortiGate

**Comment by misje** [comment]
There is small mistake with rather huge implication with the current fix: the filter mode for indicator search must be "and": pattern_type must be stix *and* the simple stix query must both match.
